authorName: default
experimentName: TLCC_come_on
trialConcurrency: 1
maxExecDuration: 1000h
maxTrialNum: 10
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner, GPTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: minimize
trial:
  command: python3 main_nni.py
  codeDir: .
  gpuNum: 1
localConfig:
  useActiveGpu: true

